repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 'latest'
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'latest' # Use the sha / tag you want to point at
    hooks:
      - id: eslint
