repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    hooks:
      - id: commitlint
        stages: [commit-msg]
    rev: v8.0.0
  - hooks:
      - args:
          - --fix
        id: eslint
    repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.14.0
  - hooks:
      - id: ggshield
        language_version: python3
        stages:
          - commit
    repo: https://github.com/gitguardian/ggshield
    rev: v1.11.0
  - hooks:
      - id: ggshield-push
        language_version: python3
        stages:
          - push
    repo: https://github.com/gitguardian/ggshield
    rev: v1.11.0
