version: "3.9"

services:
  app:
    build:
      context: .
    container_name: perpetual-mechanical-array-bot
    env_file: .env
    restart: always
    volumes:
      - ./firebase-service-acc:/app/firebase-service-acc:ro
    labels:
      - org.opencontainers.image.authors="MRDGH2821 <https://github.com/MRDGH2821>"
      - org.opencontainers.image.url=https://github.com/MRDGH2821/Perpetual-Mechanical-Array-Bot
      - org.opencontainers.image.documentation=https://github.com/MRDGH2821/Perpetual-Mechanical-Array-Bot#readme
      - org.opencontainers.image.source=https://github.com/MRDGH2821/Perpetual-Mechanical-Array-Bot
      - org.opencontainers.image.licenses=Unlicense
      - org.opencontainers.image.title="Perpetual Mechanical Array Bot"
      - org.opencontainers.image.description="Discord Bot for [Traveler Mains Server](https://discord.gg/RsdUnupKpj)"
      - org.opencontainers.image.base.name=docker.io/library/node:lts-slim
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "http://localhost:9000/"]
      interval: 30s
      timeout: 10s
      retries: 5
