version: '3.9'

services:
  app:
    build:
      context: .
    container_name: perpetual-mechanical-array-bot
    env_file: .env
    restart: always
    volumes:
      - ./firebase-service-acc:/app/firebase-service-acc:ro
