#!/usr/bin/bash
# Linux and macOS-specific commands for initialization

# Check if the script is running on GitHub Codespaces
if [[ -n "${CODESPACES}" ]]; then
  printf "Running in GitHub Codespaces.\nNo need to export any keys."
  # Add your specific commands for GitHub Codespaces here, if needed
else

  if [[ "$(uname)" == "Linux" ]]; then
    echo "Running on Linux host."
  else
    echo "Running on MacOS host."
  fi
  # Add your GPG export and import commands here for Linux and macOS

  fileContent=$(cat .devcontainer/gpg/gpg-key-id.txt)

  echo "Exporting Public Key"
  gpg -a --passphrase-file .devcontainer/gpg/gpg-key-password.txt --output .devcontainer/gpg/public-keys.asc --yes --export "$fileContent"
  echo "Exported Public Key"
  echo " "

  echo "Exporting Private Key"
  gpg -a --passphrase-file .devcontainer/gpg/gpg-key-password.txt --output .devcontainer/gpg/private-keys.asc --yes --export-secret-keys "$fileContent"
  echo "Exported Private Key"
  echo " "

  echo "Exporting Trust DB"
  gpg -a --passphrase-file .devcontainer/gpg/gpg-key-password.txt --export-ownertrust >.devcontainer/gpg/owner-trust-db.txt
  echo "Exported Trust DB"
  echo " "

fi
