#!/usr/bin/env bash
# Linux and macOS-specific commands for initialization

# Check if the script is running on GitHub Codespaces
if [[ -n "${CODESPACES}" ]] || [[ "$(uname)" == "Linux" ]]; then
  printf "Running in GitHub Codespaces/Linux host.\nNo need to export any keys."
  # Add your specific commands for GitHub Codespaces here, if needed
  exit
else

  echo "Running on MacOS host."

  # Add your GPG export and import commands here for Linux and macOS

  keyId=$(cat .devcontainer/gpg/gpg-key-id.txt)

  echo "Exporting Public Key"
  gpg -a --pinentry-mode loopback --passphrase-file .devcontainer/gpg/gpg-key-password.txt --output .devcontainer/gpg/public-keys.asc --yes --export "$keyId"
  echo "Exported Public Key"
  echo " "

  echo "Exporting Private Key"
  gpg -a --pinentry-mode loopback --passphrase-file .devcontainer/gpg/gpg-key-password.txt --output .devcontainer/gpg/private-keys.asc --yes --export-secret-keys "$keyId"
  echo "Exported Private Key"
  echo " "

  echo "Exporting Trust DB"
  gpg -a --pinentry-mode loopback --passphrase-file .devcontainer/gpg/gpg-key-password.txt --export-ownertrust >.devcontainer/gpg/owner-trust-db.txt
  echo "Exported Trust DB"
  echo " "

  exit

fi
